/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package principal;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Fayçal
 */
public class Agent extends javax.swing.JFrame {
Statement stmt;
   Connecter maConnection=new Connecter();
      ResultSet rs;
    /**
     * Creates new form Agent
     */
    public Agent() {
        initComponents();
        Table();
        Table2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTextField4a = new javax.swing.JTextField();
        jTextField5a = new javax.swing.JTextField();
        jTextField6a = new javax.swing.JTextField();
        jTextField7a = new javax.swing.JTextField();
        jTextField8a = new javax.swing.JTextField();
        jLabel4a = new javax.swing.JLabel();
        jLabel7a = new javax.swing.JLabel();
        jLabel11a = new javax.swing.JLabel();
        jTextField1a = new javax.swing.JTextField();
        jTextField2a = new javax.swing.JTextField();
        jTextField3a = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10a = new javax.swing.JLabel();
        jLabel8a = new javax.swing.JLabel();
        jLabel6a = new javax.swing.JLabel();
        jLabel5a = new javax.swing.JLabel();
        jLabel9a = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField6 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(180, 133, 113));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setAutoscrolls(true);
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane1.setFocusable(false);
        jTabbedPane1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setBackground(new java.awt.Color(180, 133, 113));
        jButton6.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Gérer les produits");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.setFocusable(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, -1, -1));

        jButton7.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(180, 133, 113));
        jButton7.setText("Attribution des prix");
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.setFocusable(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, -1, -1));

        jButton8.setBackground(new java.awt.Color(180, 133, 113));
        jButton8.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Déconnecter");
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.setFocusable(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, -1, -1));

        jLabel14.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 48)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(180, 133, 113));
        jLabel14.setText("Bienvenue cher employé");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\BabaAhmed_Ghamraci\\pic\\azerclient.jpg")); // NOI18N
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 630));

        jTabbedPane1.addTab("Produit", jPanel3);

        jPanel1.setLayout(null);

        jTextField4a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4aActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField4a);
        jTextField4a.setBounds(230, 200, 125, 22);

        jTextField5a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5aActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField5a);
        jTextField5a.setBounds(450, 160, 125, 22);
        jPanel1.add(jTextField6a);
        jTextField6a.setBounds(450, 200, 125, 22);
        jPanel1.add(jTextField7a);
        jTextField7a.setBounds(670, 160, 125, 22);
        jPanel1.add(jTextField8a);
        jTextField8a.setBounds(670, 200, 125, 22);

        jLabel4a.setFont(new java.awt.Font("Berlin Sans FB", 0, 15)); // NOI18N
        jLabel4a.setForeground(new java.awt.Color(82, 82, 82));
        jLabel4a.setText("Num_com");
        jLabel4a.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel4a);
        jLabel4a.setBounds(249, 100, 70, 22);

        jLabel7a.setFont(new java.awt.Font("Berlin Sans FB", 0, 15)); // NOI18N
        jLabel7a.setForeground(new java.awt.Color(82, 82, 82));
        jLabel7a.setText("Quantite1");
        jLabel7a.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel7a);
        jLabel7a.setBounds(149, 200, 70, 22);

        jLabel11a.setFont(new java.awt.Font("Berlin Sans FB", 0, 15)); // NOI18N
        jLabel11a.setForeground(new java.awt.Color(82, 82, 82));
        jLabel11a.setText("Quantite3");
        jLabel11a.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel11a);
        jLabel11a.setBounds(589, 200, 70, 22);

        jTextField1a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1aActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1a);
        jTextField1a.setBounds(320, 100, 125, 22);
        jPanel1.add(jTextField2a);
        jTextField2a.setBounds(570, 100, 125, 22);
        jPanel1.add(jTextField3a);
        jTextField3a.setBounds(230, 160, 125, 22);

        jButton9.setBackground(new java.awt.Color(180, 133, 113));
        jButton9.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Gérer les commandes");
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.setFocusable(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);
        jButton9.setBounds(640, 540, 250, 28);

        jButton12.setBackground(new java.awt.Color(180, 133, 113));
        jButton12.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("Valider");
        jButton12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton12.setFocusable(false);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12);
        jButton12.setBounds(360, 255, 90, 27);

        jButton22.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jButton22.setForeground(new java.awt.Color(180, 133, 113));
        jButton22.setText("Refuser");
        jButton22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton22.setFocusable(false);
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton22);
        jButton22.setBounds(490, 255, 100, 27);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255,80));

        jLabel11.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 48)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(180, 133, 113));
        jLabel11.setText("Validation des commandes");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel10a.setFont(new java.awt.Font("Berlin Sans FB", 0, 15)); // NOI18N
        jLabel10a.setForeground(new java.awt.Color(82, 82, 82));
        jLabel10a.setText("Ref Produit 3");
        jLabel10a.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel8a.setFont(new java.awt.Font("Berlin Sans FB", 0, 15)); // NOI18N
        jLabel8a.setForeground(new java.awt.Color(82, 82, 82));
        jLabel8a.setText("Ref Produit 2");
        jLabel8a.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel6a.setFont(new java.awt.Font("Berlin Sans FB", 0, 15)); // NOI18N
        jLabel6a.setForeground(new java.awt.Color(82, 82, 82));
        jLabel6a.setText("Ref Produit 1");
        jLabel6a.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel5a.setFont(new java.awt.Font("Berlin Sans FB", 0, 15)); // NOI18N
        jLabel5a.setForeground(new java.awt.Color(82, 82, 82));
        jLabel5a.setText("Num_client");
        jLabel5a.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel9a.setFont(new java.awt.Font("Berlin Sans FB", 0, 15)); // NOI18N
        jLabel9a.setForeground(new java.awt.Color(82, 82, 82));
        jLabel9a.setText("Quantite2");
        jLabel9a.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jLabel6a)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 199, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(171, 171, 171))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5a, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(408, 408, 408))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9a, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8a))
                        .addGap(136, 136, 136)
                        .addComponent(jLabel10a)
                        .addGap(305, 305, 305))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5a, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10a, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8a, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6a, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel9a, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(30, 20, 940, 270);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "num com", "num_client", "produit1", "quantite1", "produit2", "quantite2", "produit3", "quantite3"
            }
        ));
        jTable2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable2.setFocusable(false);
        jTable2.setSelectionBackground(new java.awt.Color(180, 133, 113));
        jTable2.setShowGrid(false);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable2MouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(0, 300, 1000, 190);

        jLabel13.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 22)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(180, 133, 113));
        jLabel13.setText("Consulter les commandes validées");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel13);
        jLabel13.setBounds(590, 505, 340, 26);

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\BabaAhmed_Ghamraci\\pic\\azerCm.jpg")); // NOI18N
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel10);
        jLabel10.setBounds(0, 0, 1000, 660);

        jTabbedPane1.addTab("Traitement des commandes", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 15)); // NOI18N
        jLabel1.setText("Type");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 15)); // NOI18N
        jLabel2.setText("Nom Prénom");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 170, 90, -1));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 15)); // NOI18N
        jLabel3.setText("Adresse");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 67, -1));

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 15)); // NOI18N
        jLabel4.setText("Email");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 65, -1));

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 15)); // NOI18N
        jLabel5.setText("Responsable");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 120, -1));
        jPanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 120, -1));
        jPanel2.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 120, -1));
        jPanel2.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 120, -1));

        jButton1.setBackground(new java.awt.Color(180, 133, 113));
        jButton1.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Ajouter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, -1, -1));

        jButton2.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jButton2.setText("Modifier");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, -1, -1));

        jButton3.setBackground(new java.awt.Color(180, 133, 113));
        jButton3.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Supprimer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 440, -1, -1));

        jComboBox1.setBackground(new java.awt.Color(180, 133, 113));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Revendeur", "Non Revendeur" }));
        jComboBox1.setFocusable(false);
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 120, -1));
        jPanel2.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 120, -1));

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB", 0, 15)); // NOI18N
        jLabel9.setText("Mot de passe");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 91, -1));
        jPanel2.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 120, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Numero", "Designation", "Type", "Responsable", "Adresse", "Email", "user", "Mdps"
            }
        ));
        jTable1.setFocusable(false);
        jTable1.setSelectionBackground(new java.awt.Color(180, 133, 113));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable1MouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 120, 570, 267));
        jPanel2.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 390, 170, -1));

        jButton4.setBackground(new java.awt.Color(180, 133, 113));
        jButton4.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Rechecher");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 420, -1, -1));

        jButton5.setBackground(new java.awt.Color(180, 133, 113));
        jButton5.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Gestion de inscriptions");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 540, -1, -1));

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB", 0, 15)); // NOI18N
        jLabel8.setText("Zone");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 37, -1));

        jComboBox2.setBackground(new java.awt.Color(180, 133, 113));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nord", "Sud", "Est", "Ouest" }));
        jComboBox2.setFocusable(false);
        jPanel2.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 120, -1));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255,80));

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB", 0, 15)); // NOI18N
        jLabel7.setText("Nom d'utilisateur");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel7)
                .addContainerGap(227, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(242, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(121, 121, 121))
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 370, 380));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255,80));

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 0, 15)); // NOI18N
        jLabel6.setText("Recherche par Email");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(272, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(188, 188, 188))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(279, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 590, 380));

        jLabel16.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(180, 133, 113));
        jLabel16.setText("Traiter les demandes d'inscription");
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 510, -1, -1));

        jLabel17.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 48)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(180, 133, 113));
        jLabel17.setText("Clients inscrits");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 320, 40));

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\BabaAhmed_Ghamraci\\pic\\azer3.jpg")); // NOI18N
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 630));

        jTabbedPane1.addTab("Inscription Client", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        setSize(new java.awt.Dimension(1014, 674));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String type=jComboBox1.getSelectedItem().toString();
        String designation= jTextField2.getText();
        String adresse= jTextField3.getText();
        String email= jTextField4.getText();
        String responsable=jTextField5.getText();
        String nomUtilisateur=jTextField7.getText();
        String motDePasse=jTextField8.getText();
        String zone = jComboBox2.getSelectedItem().toString();
        String requete="INSERT INTO `clients` (`numero`, `designation`, `type`, `zone`, `responsable`, `adresse`, `email`, `nom_utilisateur`, `mot_de_passe`) VALUES (Null,'"+designation+"','"+type+"','"+zone+"','"+ adresse+"','"+email+"','"+ responsable+"','"+nomUtilisateur+"','"+motDePasse+"')";

        try{
            stmt=maConnection.obtenirconnexion().createStatement();
            stmt.executeUpdate(requete);
            JOptionPane.showMessageDialog(null,"requete executée avec succès");
            Table();
        }catch(SQLException ex  ){
            System.err.println(ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String type=jComboBox1.getSelectedItem().toString();
        String designation= jTextField2.getText();
        String adresse= jTextField3.getText();
        String email= jTextField4.getText();
        String responsable=jTextField5.getText();
        String nomUtilisateur=jTextField7.getText();
        String motDePasse=jTextField8.getText();
        String zone = jComboBox2.getSelectedItem().toString();

        String requete1="select* from `clients` WHERE `email`='"+email+"'";
        String requete2="UPDATE `clients` SET `type`='"+designation+"',`designation`='"+type+"',`adresse`='"+adresse+"',`nom_utilisateur`='"+nomUtilisateur+"',`responsable`='"+responsable+"',`mot_de_passe`='"+motDePasse+"',`zone`='"+zone+"' WHERE `email`='"+email+"'";
        try{
            stmt=maConnection.obtenirconnexion().createStatement();
            rs=stmt.executeQuery(requete1);
            if(rs.next()){
                stmt.executeUpdate(requete2);
                JOptionPane.showMessageDialog(null,"requete executée avec succès");
                Table();}else{
                JOptionPane.showMessageDialog(null,"le client n'existe pas");
            }
        }catch(SQLException ex ){
            System.err.println(ex);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String email=jTextField4.getText();

        String requete1="select* from `clients` WHERE `email`='"+email+"'";

        String requete2="delete from `clients` WHERE `email`='"+email+"'";
        try{
            stmt=maConnection.obtenirconnexion().createStatement();
            rs=stmt.executeQuery(requete1);
            if(rs.next()){
                stmt.executeUpdate(requete2);
                JOptionPane.showMessageDialog(null,"requete executée avec succès");
                Table();}else{
                JOptionPane.showMessageDialog(null,"le client n'existe");
            }
        }catch(SQLException ex  ){
            System.err.println(ex);
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseReleased
        // TODO add your handling code here:
        int i=jTable1.getSelectedRow();
        DefaultTableModel model =(DefaultTableModel)jTable1.getModel();
        jComboBox1.setSelectedItem(model.getValueAt(i,1).toString());
        jTextField2.setText(model.getValueAt(i,2).toString());
        jComboBox2.setSelectedItem(model.getValueAt(i,3).toString());
        
        jTextField3.setText(model.getValueAt(i,4).toString());
        jTextField4.setText(model.getValueAt(i,5).toString());

        jTextField5.setText(model.getValueAt(i,6).toString());
         jTextField7.setText(model.getValueAt(i,7).toString());
    

    }//GEN-LAST:event_jTable1MouseReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String email=jTextField6.getText();
        System.out.print(email);
        String requete="select * from `clients` WHERE `email`='"+email+"'";
        System.out.print(requete);
        try{
            stmt=maConnection.obtenirconnexion().createStatement();
            rs=stmt.executeQuery(requete);
            if(rs.next()){
                jComboBox1.setSelectedItem(rs.getString("type"));
                jTextField2.setText(rs.getString("designation"));
                jComboBox2.setSelectedItem(rs.getString("zone"));
                jTextField3.setText(rs.getString("adresse"));
                jTextField4.setText(rs.getString("email"));
                jTextField5.setText(rs.getString("responsable"));
                jTextField7.setText(rs.getString("nom_utilisateur"));
                
            }else{
                JOptionPane.showMessageDialog(null,"le client n'existe");
            }

        }catch(SQLException ex){
            System.err.println(ex);
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        GestionInscriptions ins=new GestionInscriptions();
        ins.show();dispose(); ins.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
         Produits fenetreCom=new Produits();
         fenetreCom.show();dispose(); fenetreCom.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        AgentCommercial fenetreACM=new AgentCommercial();
        fenetreACM.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        Accueil fenetreAcc=new Accueil();
         fenetreAcc.show();dispose(); fenetreAcc.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jTable2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseReleased
        // TODO add your handling code here:
        int i=jTable2.getSelectedRow();
        DefaultTableModel model =(DefaultTableModel)jTable2.getModel();
        jTextField1a.setText(model.getValueAt(i,0).toString());
        jTextField2a.setText(model.getValueAt(i,1).toString());
        jTextField3a.setText(model.getValueAt(i,2).toString());
        jTextField4a.setText(model.getValueAt(i,3).toString());
        jTextField5a.setText(model.getValueAt(i,4).toString());
        jTextField6a.setText(model.getValueAt(i,5).toString());
        jTextField7a.setText(model.getValueAt(i,6).toString());
        jTextField8a.setText(model.getValueAt(i,7).toString());
    }//GEN-LAST:event_jTable2MouseReleased

    private void jTextField4aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4aActionPerformed

    private void jTextField5aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5aActionPerformed

    private void jTextField1aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1aActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        String numCom= jTextField1a.getText();

        int num=Integer.parseInt(numCom);

        String requete1="select* from `commandes` WHERE `num_com`='"+num+"'";
        String requete2="UPDATE `commandes` SET `valide`='oui' WHERE `num_com`='"+num+"'";

        try{
            stmt=maConnection.obtenirconnexion().createStatement();

            rs=stmt.executeQuery(requete1);  // verifier si elle existe dans la table des commandes passées par les clients
            if(rs.next()){
                stmt.executeUpdate(requete2);
                JOptionPane.showMessageDialog(null,"requete executée avec succès");
                Table2();
            }else{
                JOptionPane.showMessageDialog(null,"le commande n'existe pas");
            }
        }catch(SQLException ex){

            System.err.println(ex);
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
        String numero= jTextField1a.getText();

        int numCom=Integer.parseInt(numero);

        String requete1="select* from `commandes` WHERE `num_com`='"+numCom+"'";

        String requete2="delete from `commandes` WHERE `num_com`='"+numCom+"'";
        try{
            stmt=maConnection.obtenirconnexion().createStatement();
            rs=stmt.executeQuery(requete1); // refuser la commande => la supprimer de la table commandes

            if(rs.next()){
                stmt.executeUpdate(requete2);
                JOptionPane.showMessageDialog(null,"requete executée avec succès");
                Table2();
            }else{
                JOptionPane.showMessageDialog(null,"la commande n'existe pas");
            }
        }catch(SQLException ex  ){
            System.err.println(ex);
        }

    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        Cmd_valide fenetreCV=new Cmd_valide();
         fenetreCV.show();dispose(); fenetreCV.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton9ActionPerformed

    
     public void Table(){
         String [] client={"numero","type","designation","Zone","adresse","email","responsable","nom utilisateur"};
    String [] afficher=new String[8];
     DefaultTableModel model =new DefaultTableModel(null,client);
     try{
     stmt=maConnection.obtenirconnexion().createStatement();
         rs=stmt.executeQuery("select* from `clients`");
         while(rs.next()){
         afficher[0]=rs.getString("Numero");
         afficher[1]=rs.getString("Type");
         afficher[2]=rs.getString("Designation");
         afficher[3]=rs.getString("Zone");
         afficher[4]=rs.getString("Adresse");
         afficher[5]=rs.getString("Email");
         afficher[6]=rs.getString("Responsable");
         afficher[7]=rs.getString("Nom_utilisateur");
       
         
         model.addRow(afficher);
         }
             
             jTable1.setModel(model);
          //maConnection.close();
     }catch(Exception e){
            System.err.println(e);
     }
}
    
     public void Table2(){
    String [] commande={"num_com","num client","des_produit1","quantite1","des_produit2","quantite2","des_produit3","quantite3"};
    String [] afficher=new String[8];
     DefaultTableModel model =new DefaultTableModel(null,commande);
     try{
     stmt=maConnection.obtenirconnexion().createStatement();
         rs=stmt.executeQuery("select* from `commandes` where `valide` !='oui' ");
         while(rs.next()){
          afficher[0]=rs.getString("num_com");
         afficher[1]=rs.getString("num_client");
         afficher[2]=rs.getString("des_produit1");
         afficher[3]=rs.getString("quantite1");
        afficher[4]=rs.getString("des_produit2");
         afficher[5]=rs.getString("quantite2");
         afficher[6]=rs.getString("des_produit3");
         afficher[7]=rs.getString("quantite3");
         // afficher[8]=rs.getString("valide");
         
         model.addRow(afficher);
         }
             
             jTable2.setModel(model);
          //maConnection.close();
     }catch(Exception e){
            System.err.println(e);
     }
}
   
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel10a;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel11a;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel4a;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel5a;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel6a;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel7a;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel8a;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel9a;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1a;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField2a;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField3a;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField4a;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField5a;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField6a;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField7a;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField8a;
    // End of variables declaration//GEN-END:variables
}
