/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package principal;
import java.sql.*;
 import javax.swing.JOptionPane;
/**
 *
 * @author Fayçal
 */
public class Commander extends javax.swing.JFrame {
Statement stmt;
      Connecter maConnection=new Connecter();
      ResultSet rs;
      int i=0;int q1=0,q2=0,q3=0;
      public static   String [] radio= new String [3];
    /**
     * Creates new form Commander
     */
    public Commander() {
        initComponents();
        jLabel13.setVisible(false);jSpinner3.setEnabled(false);
        jLabel16.setVisible(false);jSpinner2.setEnabled(false);
        jLabel4.setVisible(false);jSpinner1.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jCheckBox4 = new javax.swing.JCheckBox();
        jLabel16 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        jCheckBox8 = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        jCheckBox5 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jSpinner3 = new javax.swing.JSpinner();
        jLabel15 = new javax.swing.JLabel();
        jCheckBox7 = new javax.swing.JCheckBox();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(180, 133, 113));
        jButton1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Commander");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 530, -1, -1));

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("La quantité a dépasser le stock");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 210, 190, 20));

        jSpinner1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jSpinner1.setFocusable(false);
        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });
        jSpinner1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSpinner1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jSpinner1MousePressed(evt);
            }
        });
        jPanel1.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 180, 45, -1));

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 15)); // NOI18N
        jLabel1.setText("Quantite");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 180, -1, -1));

        jCheckBox1.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jCheckBox1.setText("Lait cru");
        jCheckBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCheckBox1.setFocusable(false);
        jCheckBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox1MouseClicked(evt);
            }
        });
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 170, -1, -1));

        jCheckBox2.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jCheckBox2.setText("Lait pasteurisé");
        jCheckBox2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCheckBox2.setFocusable(false);
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));

        jCheckBox3.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jCheckBox3.setText("Lait stérilisé");
        jCheckBox3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCheckBox3.setFocusable(false);
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, -1, -1));

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB", 0, 13)); // NOI18N
        jLabel8.setText("U226");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, 30, -1));

        jCheckBox4.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jCheckBox4.setText("Lait UHT");
        jCheckBox4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCheckBox4.setFocusable(false);
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, -1, -1));

        jLabel16.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 0, 0));
        jLabel16.setText("La quantité a dépasser le stock");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 350, -1, -1));

        jSpinner2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jSpinner2.setFocusable(false);
        jSpinner2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner2StateChanged(evt);
            }
        });
        jPanel1.add(jSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 320, 45, -1));

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 15)); // NOI18N
        jLabel2.setText("Quantite");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 320, -1, 20));

        jCheckBox9.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jCheckBox9.setText("Beurre");
        jCheckBox9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCheckBox9.setFocusable(false);
        jCheckBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox9ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 320, 71, -1));

        jCheckBox6.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jCheckBox6.setText("fromage");
        jCheckBox6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCheckBox6.setFocusable(false);
        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, -1, -1));

        jLabel10.setFont(new java.awt.Font("Berlin Sans FB", 0, 13)); // NOI18N
        jLabel10.setText("FP1104");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 40, -1));

        jCheckBox8.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jCheckBox8.setText(" crème fraiche");
        jCheckBox8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCheckBox8.setFocusable(false);
        jCheckBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox8ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, -1, -1));

        jLabel13.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 0, 0));
        jLabel13.setText("La quantité a dépasser le stock");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 500, -1, -1));

        jCheckBox5.setFont(new java.awt.Font("Berlin Sans FB", 0, 15)); // NOI18N
        jCheckBox5.setText("Lait concentré");
        jCheckBox5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCheckBox5.setFocusable(false);
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 470, -1, -1));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 15)); // NOI18N
        jLabel3.setText("Quantite");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 457, -1, 40));

        jSpinner3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jSpinner3.setFocusable(false);
        jSpinner3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner3StateChanged(evt);
            }
        });
        jPanel1.add(jSpinner3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 470, 45, -1));

        jLabel15.setFont(new java.awt.Font("Berlin Sans FB", 0, 13)); // NOI18N
        jLabel15.setText("C1122");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 490, 30, 20));

        jCheckBox7.setFont(new java.awt.Font("Berlin Sans FB", 0, 15)); // NOI18N
        jCheckBox7.setText("Yaourt");
        jCheckBox7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCheckBox7.setFocusable(false);
        jCheckBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox7ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 470, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\BabaAhmed_Ghamraci\\pic\\past1.png")); // NOI18N
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 40, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon("C:\\BabaAhmed_Ghamraci\\pic\\9stirili.png")); // NOI18N
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\BabaAhmed_Ghamraci\\pic\\ht.png")); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, -1, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon("C:\\BabaAhmed_Ghamraci\\pic\\cru.png")); // NOI18N
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, -1, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon("C:\\BabaAhmed_Ghamraci\\pic\\pres.png")); // NOI18N
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 90, 80));

        jLabel21.setIcon(new javax.swing.ImageIcon("C:\\BabaAhmed_Ghamraci\\pic\\crem.png")); // NOI18N
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, -1, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon("C:\\BabaAhmed_Ghamraci\\pic\\yaourt.png")); // NOI18N
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, -1, -1));

        jLabel23.setIcon(new javax.swing.ImageIcon("C:\\BabaAhmed_Ghamraci\\pic\\cenc.png")); // NOI18N
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, -1, -1));

        jLabel24.setIcon(new javax.swing.ImageIcon("C:\\BabaAhmed_Ghamraci\\pic\\ber.png")); // NOI18N
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, -1, 70));

        jLabel25.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(180, 133, 113));
        jLabel25.setText("Nos laits");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));

        jLabel26.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(180, 133, 113));
        jLabel26.setText("Nos produit salé");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        jLabel27.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(180, 133, 113));
        jLabel27.setText("Nos produits sucré");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 405, -1, -1));

        jLabel28.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 48)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(180, 133, 113));
        jLabel28.setText("Nos Produits Laitiers");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 460, 40));

        jLabel29.setIcon(new javax.swing.ImageIcon("C:\\BabaAhmed_Ghamraci\\pic\\icons8.png")); // NOI18N
        jLabel29.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel29.setFocusable(false);
        jLabel29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel29MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255,80));

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 13)); // NOI18N
        jLabel5.setText("C223");

        jLabel31.setFont(new java.awt.Font("Berlin Sans FB", 0, 13)); // NOI18N
        jLabel31.setText("Reference :");

        jLabel32.setFont(new java.awt.Font("Berlin Sans FB", 0, 13)); // NOI18N
        jLabel32.setText("Reference :");

        jLabel33.setFont(new java.awt.Font("Berlin Sans FB", 0, 13)); // NOI18N
        jLabel33.setText("Reference :");

        jLabel34.setFont(new java.awt.Font("Berlin Sans FB", 0, 13)); // NOI18N
        jLabel34.setText("Reference :");

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB", 0, 13)); // NOI18N
        jLabel7.setText("S0225");

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 0, 13)); // NOI18N
        jLabel6.setText("P0224");

        jLabel35.setFont(new java.awt.Font("Berlin Sans FB", 0, 13)); // NOI18N
        jLabel35.setText("Reference :");

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB", 0, 13)); // NOI18N
        jLabel9.setText("B0013");

        jLabel36.setFont(new java.awt.Font("Berlin Sans FB", 0, 13)); // NOI18N
        jLabel36.setText("Reference :");

        jLabel11.setFont(new java.awt.Font("Berlin Sans FB", 0, 13)); // NOI18N
        jLabel11.setText("CF1201");

        jLabel37.setFont(new java.awt.Font("Berlin Sans FB", 0, 13)); // NOI18N
        jLabel37.setText("Reference :");

        jLabel38.setFont(new java.awt.Font("Berlin Sans FB", 0, 13)); // NOI18N
        jLabel38.setText("Reference :");
        jLabel38.setToolTipText("");

        jLabel39.setFont(new java.awt.Font("Berlin Sans FB", 0, 13)); // NOI18N
        jLabel39.setText("Reference :");

        jLabel14.setFont(new java.awt.Font("Berlin Sans FB", 0, 13)); // NOI18N
        jLabel14.setText("Y0012");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel37)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addGap(75, 75, 75)
                        .addComponent(jLabel32)
                        .addGap(102, 102, 102)
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(200, 200, 200))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel36)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(127, 127, 127)
                        .addComponent(jLabel35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(276, 276, 276))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel39)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addGap(75, 75, 75)
                .addComponent(jLabel38)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(jLabel5)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33)
                    .addComponent(jLabel34)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addGap(129, 129, 129)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(jLabel9)
                    .addComponent(jLabel36)
                    .addComponent(jLabel11)
                    .addComponent(jLabel37))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(jLabel39)
                    .addComponent(jLabel14))
                .addGap(63, 63, 63))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 910, 540));

        jLabel30.setIcon(new javax.swing.ImageIcon("C:\\BabaAhmed_Ghamraci\\pic\\aya.jpg")); // NOI18N
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, 0, -1, 600));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1186, 600);

        setSize(new java.awt.Dimension(1029, 617));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
     //   client_cmd_vu fa = new client_cmd_vu();
          if(radio[0] != ""){  q1=(int) jSpinner1.getValue();}
          if(radio[1] != ""){  q2=(int) jSpinner2.getValue();}
          if(radio[2] != ""){  q3=(int) jSpinner3.getValue();}
          
           String requete1="select* from `clients` WHERE `nom_utilisateur`='"+Login.nomUtilisateur+"'";
           //String requete1="select* from `clients` WHERE `nom_utilisateur`='mrfxl'";
           String requete2="";
            //String produit1 = buttonGroup1.getClass().toString();
            //System.out.print(produit1);
         
          // String requete2="INSERT INTO `commandes`(`num_client`, `des_produit1`, `quantite1`, `des_produit2`, `quantite2`, `des_produit3`, `quantite3`) VALUES ('"+num+"','"+radio[0]+"','"+ q1+"','"+radio[1]+"','"+q2+"','"+radio[2]+"','"+q3+")" ;
       
           if( jLabel16.isVisible()==false  ){ 
               if(jLabel4.isVisible()==false){
                   if (jLabel13.isVisible()== false){
                       try{
          stmt=maConnection.obtenirconnexion().createStatement();
            rs=stmt.executeQuery(requete1);
         if(rs.next()){
              int num=Integer.parseInt(rs.getString("numero"));
          requete2="INSERT INTO `commandes`(`num_client`, `des_produit1`, `quantite1`, `des_produit2`, `quantite2`, `des_produit3`, `quantite3`, `valide`) VALUES ('"+num+"','"+radio[0]+"','"+ q1+"','"+radio[1]+"','"+q2+"','"+radio[2]+"','"+q3+"','')" ;
          //fa.Table();
         }
          stmt.executeUpdate(requete2);
          JOptionPane.showMessageDialog(null,"requete executée avec succès");
         
           
       }catch(SQLException ex){
       
        System.err.println(ex);
       }
                   }else{
                       JOptionPane.showMessageDialog(null,"Vous avez depasse le stock");
                   }
               }else {
                   JOptionPane.showMessageDialog(null,"Vous avez depasse le stock");
               }
            
               
           } else {
                    JOptionPane.showMessageDialog(null,"Vous avez depasse le stock");
                    }
           
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        
        if(jCheckBox1.isSelected()){
            jSpinner1.setEnabled(true);
            jSpinner1.setValue(0);
            jCheckBox2.setEnabled(false);
            jCheckBox3.setEnabled(false);
            jCheckBox4.setEnabled(false);
            radio[0]=jLabel5.getText();
        }else{
            jCheckBox2.setEnabled(true);
            jCheckBox3.setEnabled(true);
            jCheckBox4.setEnabled(true);
            jSpinner1.setEnabled(false);
            jLabel4.setVisible(false);
            radio[0]="";
        }
        
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox1MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jCheckBox1MouseClicked

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
        if(jCheckBox2.isSelected()){
            jSpinner1.setEnabled(true);
            jSpinner1.setValue(0);
            jCheckBox1.setEnabled(false);
            jCheckBox3.setEnabled(false);
            jCheckBox4.setEnabled(false);
            radio[0]=jLabel6.getText();
        }else{
            jCheckBox1.setEnabled(true);
            jCheckBox3.setEnabled(true);
            jCheckBox4.setEnabled(true);
            jSpinner1.setEnabled(false);
            jLabel4.setVisible(false);
            radio[0]="";
        }
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
        if(jCheckBox3.isSelected()){
            jSpinner1.setEnabled(true);
            jSpinner1.setValue(0);
            jCheckBox2.setEnabled(false);
            jCheckBox1.setEnabled(false);
            jCheckBox4.setEnabled(false);
            radio[0]=jLabel7.getText();
        }else{
            jCheckBox2.setEnabled(true);
            jCheckBox1.setEnabled(true);
            jCheckBox4.setEnabled(true);
            jSpinner1.setEnabled(false);
            jLabel4.setVisible(false);
            radio[0]="";
        }
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        // TODO add your handling code here:
        if(jCheckBox4.isSelected()){
            jSpinner1.setEnabled(true);
            jSpinner1.setValue(0);
            jCheckBox2.setEnabled(false);
            jCheckBox3.setEnabled(false);
            jCheckBox1.setEnabled(false);
            radio[0]=jLabel8.getText();
        }else{
            jCheckBox2.setEnabled(true);
            jCheckBox3.setEnabled(true);
            jCheckBox1.setEnabled(true);
            jSpinner1.setEnabled(false);
            jLabel4.setVisible(false);
            radio[0]="";
        }
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox9ActionPerformed
        // TODO add your handling code here:
        if(jCheckBox9.isSelected()){
            jSpinner2.setEnabled(true);
            jSpinner2.setValue(0);
            jCheckBox6.setEnabled(false);
            jCheckBox8.setEnabled(false);
          
            radio[1]=jLabel9.getText();
        }else{
            jCheckBox8.setEnabled(true);
            jCheckBox6.setEnabled(true);
            jSpinner2.setEnabled(false);
            jLabel16.setVisible(false);
            radio[1]="";
        }
    }//GEN-LAST:event_jCheckBox9ActionPerformed

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
        // TODO add your handling code here:
        if(jCheckBox6.isSelected()){
              jSpinner2.setEnabled(true);
            jSpinner2.setValue(0);
            jCheckBox9.setEnabled(false);
            jCheckBox8.setEnabled(false);
          
            radio[1]=jLabel10.getText();
        }else{
            jCheckBox8.setEnabled(true);
            jCheckBox9.setEnabled(true);
        jSpinner2.setEnabled(false);
            jLabel16.setVisible(false);
            radio[1]="";
        }
    }//GEN-LAST:event_jCheckBox6ActionPerformed

    private void jCheckBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox8ActionPerformed
        // TODO add your handling code here:
        if(jCheckBox8.isSelected()){
               jSpinner2.setEnabled(true);
            jSpinner2.setValue(0);
            jCheckBox6.setEnabled(false);
            jCheckBox9.setEnabled(false);
          
            radio[1]=jLabel11.getText();
        }else{
            jCheckBox9.setEnabled(true);
            jCheckBox6.setEnabled(true);
        jSpinner2.setEnabled(false);
            jLabel16.setVisible(false);
            radio[1]="";
        }
    }//GEN-LAST:event_jCheckBox8ActionPerformed

    private void jCheckBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox7ActionPerformed
        // TODO add your handling code here:
        if(jCheckBox7.isSelected()){
             jSpinner3.setEnabled(true);
            jSpinner3.setValue(0);
            jCheckBox5.setEnabled(false);
           
          
            radio[2]=jLabel14.getText();
        }else{
            jCheckBox5.setEnabled(true);
            jSpinner3.setEnabled(false);
            jLabel13.setVisible(false);
       
            radio[2]="";
        }
    }//GEN-LAST:event_jCheckBox7ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        // TODO add your handling code here:
        if(jCheckBox5.isSelected()){
            jSpinner3.setEnabled(true);
            jSpinner3.setValue(0);
            jCheckBox7.setEnabled(false);
           
          
            radio[2]=jLabel15.getText();
        }else{
            jCheckBox7.setEnabled(true);
            jSpinner3.setEnabled(false);
            jLabel13.setVisible(false);
       
            radio[2]="";
        }
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jSpinner1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSpinner1MouseClicked
        // TODO add your handling code here:
            
    }//GEN-LAST:event_jSpinner1MouseClicked

    private void jSpinner1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSpinner1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSpinner1MousePressed

    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
        // TODO add your handling code here:
        jLabel4.setVisible(false);
        if(radio[0] != ""){  
            q1=(int) jSpinner1.getValue();
            
            String requete1="select* from `produits` WHERE `references`='"+radio[0]+"'";
           
            try{
            stmt=maConnection.obtenirconnexion().createStatement();
            rs=stmt.executeQuery(requete1);
            if(rs.next()){
               int Q =Integer.parseInt(rs.getString("stock")); 
               
               if(q1>Q){
                   jLabel4.setVisible(true);
               }
               
            }
            }catch (Exception e) {
            e.printStackTrace();
            }
            
        }else{
            jLabel4.setVisible(false);
        }
    }//GEN-LAST:event_jSpinner1StateChanged

    private void jSpinner2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner2StateChanged
        // TODO add your handling code here:
         jLabel16.setVisible(false);
        if(radio[1] != ""){  
            q2=(int) jSpinner2.getValue();
            
            String requete1="select* from `produits` WHERE `references`='"+radio[1]+"'";
            try{
            stmt=maConnection.obtenirconnexion().createStatement();
            rs=stmt.executeQuery(requete1);
            if(rs.next()){
               int Q =Integer.parseInt(rs.getString("stock")); 
               
               if(q2>Q){
                   jLabel16.setVisible(true);
               }
               
            }
            }catch (Exception e) {
            e.printStackTrace();
            }
            
        }else{
            jLabel16.setVisible(false);
        }
    }//GEN-LAST:event_jSpinner2StateChanged

    private void jSpinner3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner3StateChanged
        // TODO add your handling code here:
         jLabel13.setVisible(false);
        if(radio[2] != ""){  
            q3=(int) jSpinner3.getValue();
            
            String requete1="select* from `produits` WHERE `references`='"+radio[2]+"'";
            try{
            stmt=maConnection.obtenirconnexion().createStatement();
            rs=stmt.executeQuery(requete1);
            if(rs.next()){
               int Q =Integer.parseInt(rs.getString("stock")); 
               
               if(q3>Q){
                   jLabel13.setVisible(true);
               }
               
            }
            }catch (Exception e) {
            e.printStackTrace();
            }
            
        }else{
            jLabel13.setVisible(false);
        }
    }//GEN-LAST:event_jSpinner3StateChanged

    private void jLabel29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MouseClicked
        // TODO add your handling code here:
         Fclient fenetreC=new Fclient();
         fenetreC.show();dispose(); fenetreC.setLocationRelativeTo(null);
    }//GEN-LAST:event_jLabel29MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Commander.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Commander.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Commander.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Commander.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Commander().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    // End of variables declaration//GEN-END:variables
}
