/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package principal;
import java.sql.*;
//import java.util.Date;
 import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Fayçal
 */
public class directeur extends javax.swing.JFrame {
 Statement stmt;
  Connecter maConnection=new Connecter();
      ResultSet rs;
    /**
     * Creates new form directeur
     */
    public directeur() {
        initComponents();jTextField5.setEnabled(false);
        Table();
        Table1();
        Table2();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        jFormattedTextField4 = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(180, 133, 113));
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(180, 133, 113));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Plan de vente");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 660, -1));
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 80, -1));

        jLabel10.setFont(new java.awt.Font("Berlin Sans FB", 0, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(82, 82, 82));
        jLabel10.setText("Etablir un objectif ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane4.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 346, 104));

        jLabel12.setFont(new java.awt.Font("Berlin Sans FB", 0, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(82, 82, 82));
        jLabel12.setText("Responsable");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, -1, -1));
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 100, -1));

        jLabel13.setFont(new java.awt.Font("Berlin Sans FB", 0, 15)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(82, 82, 82));
        jLabel13.setText("Zone");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, 43, -1));

        jComboBox1.setBackground(new java.awt.Color(180, 133, 113));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nord", "Sud", "Est", "Ouest" }));
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBox1.setFocusable(false);
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, 69, -1));

        jLabel14.setFont(new java.awt.Font("Berlin Sans FB", 0, 15)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(82, 82, 82));
        jLabel14.setText("Date Début");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 170, -1, -1));

        try {
            jFormattedTextField3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-## ##:##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(jFormattedTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, 118, -1));

        try {
            jFormattedTextField4.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-## ##:##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(jFormattedTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 190, 118, -1));

        jLabel15.setFont(new java.awt.Font("Berlin Sans FB", 0, 15)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(82, 82, 82));
        jLabel15.setText("Date fin");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 170, -1, -1));

        jButton5.setFont(new java.awt.Font("Berlin Sans FB", 0, 15)); // NOI18N
        jButton5.setForeground(new java.awt.Color(180, 133, 113));
        jButton5.setText("Ajouter");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.setFocusable(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 230, -1, -1));

        jButton4.setBackground(new java.awt.Color(180, 133, 113));
        jButton4.setFont(new java.awt.Font("Berlin Sans FB", 0, 15)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Visualiser les zones");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setFocusable(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, -1, -1));

        jLabel11.setFont(new java.awt.Font("Berlin Sans FB", 0, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(82, 82, 82));
        jLabel11.setText("Table des objectif : ");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable3.setFocusable(false);
        jTable3.setSelectionBackground(new java.awt.Color(180, 133, 113));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable3MouseReleased(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 925, 144));

        jButton6.setBackground(new java.awt.Color(180, 133, 113));
        jButton6.setFont(new java.awt.Font("Berlin Sans FB", 0, 15)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Modifier");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.setFocusable(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, -1, -1));

        jButton7.setFont(new java.awt.Font("Berlin Sans FB", 0, 15)); // NOI18N
        jButton7.setForeground(new java.awt.Color(180, 133, 113));
        jButton7.setText("Supprimer");
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.setFocusable(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 460, -1, -1));

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB", 0, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(82, 82, 82));
        jLabel9.setText("Donner le numero de l'objectif :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 460, -1, -1));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 460, 173, -1));

        jButton3.setBackground(new java.awt.Color(180, 133, 113));
        jButton3.setFont(new java.awt.Font("Berlin Sans FB", 0, 15)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Rechercher");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setFocusable(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 490, -1, -1));

        jLabel17.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(82, 82, 82));
        jLabel17.setText("Num objectif");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255,80));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 950, 440));

        jButton8.setBackground(new java.awt.Color(180, 133, 113));
        jButton8.setFont(new java.awt.Font("Berlin Sans FB", 0, 15)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Déconnecter");
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.setFocusable(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 40, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\BabaAhmed_Ghamraci\\pic\\azer.jpg")); // NOI18N
        jLabel16.setText("jLabel16");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 620));

        jTabbedPane1.addTab("Plan de vente", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setFont(new java.awt.Font("Berlin Sans FB", 0, 15)); // NOI18N
        jButton2.setForeground(new java.awt.Color(180, 133, 113));
        jButton2.setText("Consulter");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 224, -1, -1));
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 224, 106, -1));

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(82, 82, 82));
        jLabel5.setText("Donner le numero de commande :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 227, -1, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255,80));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "num_com", "num_client", "des_client", "produit1", "Q1", "produit2", "Q2", "produit3", "Q3", "prix", "date"
            }
        ));
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable1.setFocusable(false);
        jTable1.setSelectionBackground(new java.awt.Color(180, 133, 113));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable1MouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable2.setFocusable(false);
        jTable2.setSelectionBackground(new java.awt.Color(180, 133, 113));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable2MouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(180, 133, 113));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Vos opération de vente (Factures)");

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(180, 133, 113));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Vos Bilan");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 41, -1, 480));

        jButton1.setFont(new java.awt.Font("Berlin Sans FB", 0, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(180, 133, 113));
        jButton1.setText("Calculer");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, -1, -1));
        jPanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 80, -1));

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(82, 82, 82));
        jLabel4.setText("Chiffre d'affaire du mois :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(82, 82, 82));
        jLabel2.setText("Date début :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-## ##:##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(jFormattedTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 105, -1));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(82, 82, 82));
        jLabel3.setText("Date fin :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, -1, -1));

        try {
            jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-## ##:##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(jFormattedTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 118, -1));

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(180, 133, 113));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Etablir le bilan entre deux date");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 413, -1));
        jPanel2.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 80, -1));

        jLabel20.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("pour le comparer avec le nouveau CA");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255,80));

        jLabel19.setFont(new java.awt.Font("Berlin Sans FB", 0, 15)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Veuillez choisir un CA de vos bilan");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel19)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(164, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(39, 39, 39))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 430, 220));

        jLabel18.setIcon(new javax.swing.ImageIcon("C:\\BabaAhmed_Ghamraci\\pic\\azerCm.jpg")); // NOI18N
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 620));

        jTabbedPane1.addTab("Bilan de vente", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String DateDeb1=jFormattedTextField1.getText();
        String Datefin1=jFormattedTextField2.getText();
        //Date DateDeb=jDateChooser1.getDate();
        //String Datefin=jDateChooser2.getDate().toString();
        String CAapr =jTextField6.getText();
        int CAprevu;
        if (CAapr.equals("")){
            CAprevu = 999999999;
        }else{
              CAprevu= Integer.parseInt(jTextField6.getText());
        }
      

        int CA=0;
        String requete1="select `prix` from `factures`  WHERE `date` BETWEEN '"+DateDeb1+"' AND '"+Datefin1+"'";
        String  requete2="";

        //.............calculer le CA
        try{

            stmt=maConnection.obtenirconnexion().createStatement();
            rs=stmt.executeQuery(requete1);
            while(rs.next()){

                CA=CA+Integer.parseInt(rs.getString("prix"));

            }

            requete2="INSERT INTO `bilans`(`date_deb`, `date_fin`, `CA`) VALUES ('"+DateDeb1+"','"+Datefin1+"',"+CA+")";
            System.out.print(requete2);
            // CLE primaire dans la table bilan est la cle composée (date_deb,date_fin)

            //...... enregistrer le chiffre d'affaires dans la table bilans
           // if(rs.next()){
                try{
                    stmt=maConnection.obtenirconnexion().createStatement();

                    stmt.executeUpdate(requete2);
                    JOptionPane.showMessageDialog(null,"requete executée avec succès");
                          Table1();
                }catch(SQLException ex){
                    System.err.println(ex);
                }
          //  }

            
            // afficher le chiffre d'affaire au directeur
            Integer chiffre=new Integer(CA);
            String  chiffreA= chiffre.toString();
            jTextField3.setText(chiffreA);
            if(CA>=CAprevu) {
                JOptionPane.showMessageDialog(null," félicitations ! objectif atteint");
            }else{
                JOptionPane.showMessageDialog(null," Attention ! chiffre d'affaires enregistré inferieur au chiffre prevu");
            }

        }catch(SQLException ex){
            System.err.println(ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
      Facturebis fenetreFacture= new Facturebis();
      
      int numCom= Integer.parseInt(jTextField1.getText());
          
         String requete1="select* from `factures` WHERE `num_com`="+numCom;
        try{

            stmt=maConnection.obtenirconnexion().createStatement();
            rs=stmt.executeQuery(requete1);
            if(rs.next()){

                  fenetreFacture.jTextField1.setText(rs.getString("num_com"));
                  fenetreFacture.jTextField2.setText(rs.getString("num_client"));
                  fenetreFacture.jTextField3.setText(rs.getString("des_client"));
                 fenetreFacture.jTextField4.setText(rs.getString("des_produit1"));
                  fenetreFacture.jTextField5.setText(rs.getString("quantite2"));
                  fenetreFacture.jTextField6.setText(rs.getString("des_produit2"));
                 fenetreFacture. jTextField7.setText(rs.getString("quantite2"));
                  fenetreFacture.jTextField8.setText(rs.getString("des_produit3"));
                 fenetreFacture.jTextField9.setText(rs.getString("quantite3"));
                  fenetreFacture.jTextField10.setText(rs.getString("prix"));
                  fenetreFacture.jTextField11.setText(rs.getString("date"));
                 //JOptionPane.showMessageDialog(null,"requete executée avec succès");
                 fenetreFacture.setVisible(true);
                 
                
            }else{

                JOptionPane.showMessageDialog(null,"la facture n'existe pas");
            }

        }catch(SQLException ex){
            System.err.println(ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseReleased
        // TODO add your handling code here:
        int i=jTable1.getSelectedRow();
        DefaultTableModel model =(DefaultTableModel)jTable1.getModel();
     jTextField1.setText(model.getValueAt(i,0).toString());
        
    }//GEN-LAST:event_jTable1MouseReleased

    private void jTable3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseReleased
        // TODO add your handling code here:
        
        int i=jTable3.getSelectedRow();
        DefaultTableModel model =(DefaultTableModel)jTable3.getModel();
        jTextField5.setText(model.getValueAt(i,0).toString());
        jTextArea1.setText(model.getValueAt(i,1).toString());
        jTextField4.setText(model.getValueAt(i,2).toString());
        jComboBox1.setSelectedItem(model.getValueAt(i,3).toString());
       jFormattedTextField3.setText(model.getValueAt(i,4).toString());
        jFormattedTextField4.setText(model.getValueAt(i,5).toString());
    }//GEN-LAST:event_jTable3MouseReleased

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String objectif= jTextArea1.getText();
         int employeRes= Integer.parseInt(jTextField4.getText());
        String zoneCible=jComboBox1.getSelectedItem().toString();
         String DateDeb=jFormattedTextField3.getText();
        String Datefin=jFormattedTextField4.getText();
        String requete2="INSERT INTO `plans`(`num_plan`, `objectif`, `employe_res`, `zone_cible`, `date_deb`, `date_fin`) VALUES (Null,'"+objectif+"','"+employeRes+"','"+zoneCible+"','"+DateDeb+"','"+Datefin+"')";
           
                try{
                    stmt=maConnection.obtenirconnexion().createStatement();

                    stmt.executeUpdate(requete2);
                    JOptionPane.showMessageDialog(null,"requete executée avec succès");
                  Table2();
                }catch(SQLException ex){
                    System.err.println(ex);
                }
       
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
         int numPlan= Integer.parseInt(jTextField5.getText());
            String objectif= jTextArea1.getText();
        int employeRes= Integer.parseInt(jTextField4.getText());
        String zoneCible=jComboBox1.getSelectedItem().toString();
         String DateDeb=jFormattedTextField3.getText();
        String Datefin=jFormattedTextField4.getText();
       
         
           String requete1="select* from `plans` WHERE `num_plan`="+numPlan;
         String requete2="UPDATE `plans` SET `objectif`='"+objectif+"',`employe_res`="+employeRes+",`zone_cible`='"+zoneCible+"',`date_deb`='"+DateDeb+"',`date_fin`='"+Datefin+"' WHERE `num_plan`="+numPlan;
       
         try{
          stmt=maConnection.obtenirconnexion().createStatement();
          rs=stmt.executeQuery(requete1);
          if(rs.next()){
          stmt.executeUpdate(requete2);
           JOptionPane.showMessageDialog(null,"requete executée avec succès");
          Table2();
          }else{
          JOptionPane.showMessageDialog(null,"le plan que vous voulez modifier n'existe pas!");
          }
        }catch(SQLException ex){
        System.err.println(ex);
        }
       
       
       
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        int numPlan= Integer.parseInt(jTextField5.getText());
       
       
          String requete1="select* from `plans` WHERE `num_plan`="+numPlan;  
            String requete2="delete from `plans` WHERE `num_plan`="+numPlan;
           try{
         
          stmt=maConnection.obtenirconnexion().createStatement();
            rs=stmt.executeQuery(requete1);
            if(rs.next()){
          stmt.executeUpdate(requete2);
          JOptionPane.showMessageDialog(null,"requete executée avec succès");
          Table2();
            }else{
                JOptionPane.showMessageDialog(null,"la plan que vous voulez supprimer  n'existe pas");
            }
         
          }catch(SQLException ex){
         
           System.err.println(ex);
         
          }
       
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int numPlan= Integer.parseInt(jTextField2.getText());
        String requete1="select* from `plans` WHERE `num_plan`="+numPlan;  
       
         try{
                    stmt=maConnection.obtenirconnexion().createStatement();

                   rs=stmt.executeQuery(requete1);
                   if(rs.next()){
                   
                   
         jTextField5.setText(rs.getString("num_plan"));
        jTextArea1.setText(rs.getString("objectif"));
        jTextField4.setText(rs.getString("employe_res"));
        jComboBox1.setSelectedItem(rs.getString("zone_cible"));
       jFormattedTextField3.setText(rs.getString("date_deb"));
        jFormattedTextField4.setText(rs.getString("date_fin"));
                   
                   }
                   
                   
                   
                   
                  Table2();
                }catch(SQLException ex){
                    System.err.println(ex);
                }
       
       
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         zones fenetre= new zones();
       
          String [] zone={"zone","client","type"};
    String [] afficher=new String[3];
     DefaultTableModel model =new DefaultTableModel(null,zone);
     try{
     stmt=maConnection.obtenirconnexion().createStatement();
         rs=stmt.executeQuery("select `zone`, `numero`, `type` from `clients` ORDER BY `zone`");
         while(rs.next()){
         afficher[0]=rs.getString("zone");
          afficher[1]=rs.getString("numero");
         afficher[2]=rs.getString("type");  
             
       
         model.addRow(afficher);
         }
             
            fenetre.jTable1.setModel(model);
          //maConnection.close();
     }catch(Exception e){
            System.err.println(e);
     }
        fenetre.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        Accueil fenetreAcc=new Accueil();
         fenetreAcc.show();dispose(); fenetreAcc.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jTable2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseReleased
        // TODO add your handling code here:
       int i=jTable2.getSelectedRow();
        DefaultTableModel model =(DefaultTableModel)jTable2.getModel();
     jTextField6.setText(model.getValueAt(i,2).toString());
    }//GEN-LAST:event_jTable2MouseReleased
  
     
     public void Table(){
   String [] facture={"num_com","num client","des_client","des_produit1","quantite1","des_produit2","quantite2","des_produit3","quantite3","prix","date"};
    String [] afficher=new String[11];
     DefaultTableModel model =new DefaultTableModel(null,facture);
     try{
     stmt=maConnection.obtenirconnexion().createStatement();
         rs=stmt.executeQuery("SELECT * FROM `factures` ORDER BY `factures`.`date` ASC ");
         while(rs.next()){
         afficher[0]=rs.getString("num_com");
         afficher[1]=rs.getString("num_client");
         afficher[2]=rs.getString("des_client");
         afficher[3]=rs.getString("des_produit1");
         afficher[4]=rs.getString("quantite1");
          afficher[5]=rs.getString("des_produit2");
         afficher[6]=rs.getString("quantite2");
           afficher[7]=rs.getString("des_produit3");
         afficher[8]=rs.getString("quantite3");
          afficher[9]=rs.getString("prix");
          afficher[10]=rs.getString("date");
         model.addRow(afficher);
         }
             
             jTable1.setModel(model);
          //maConnection.close();
     }catch(Exception e){
            System.err.println(e);
     }
}
    
    public void Table1(){
   String [] bilan={"date_deb","date_fin","CA"};
    String [] afficher=new String[3];
     DefaultTableModel model =new DefaultTableModel(null,bilan);
     try{
     stmt=maConnection.obtenirconnexion().createStatement();
         rs=stmt.executeQuery("select* from `bilans`");
         while(rs.next()){
         afficher[0]=rs.getString("date_deb");
         afficher[1]=rs.getString("date_fin");
         afficher[2]=rs.getString("CA");
        
         model.addRow(afficher);
         }
             
             jTable2.setModel(model);
          //maConnection.close();
     }catch(Exception e){
            System.err.println(e);
     }
}
      
    public void Table2(){
   String [] plan={"num_plan","objectif","eployé res","zone ciblée","date_deb","date_fin"};
    String [] afficher=new String[6];
     DefaultTableModel model =new DefaultTableModel(null,plan);
     try{
     stmt=maConnection.obtenirconnexion().createStatement();
         rs=stmt.executeQuery("select* from `plans`");
         while(rs.next()){
         afficher[0]=rs.getString("num_plan");
          afficher[1]=rs.getString("objectif");
         afficher[2]=rs.getString("employe_res");  
             afficher[3]=rs.getString("zone_cible");
         afficher[4]=rs.getString("date_deb");
         afficher[5]=rs.getString("date_fin");
       
       
         model.addRow(afficher);
         }
             
             jTable3.setModel(model);
          //maConnection.close();
     }catch(Exception e){
            System.err.println(e);
     }
}
      
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(directeur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(directeur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(directeur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(directeur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new directeur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JFormattedTextField jFormattedTextField4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
