/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package principal;
import java.sql.*;
import javax.lang.model.element.VariableElement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
/**
 *
 * @author Fayçal
 */
public class Produits extends javax.swing.JFrame {
    Statement stmt;
   Connecter maConnection=new Connecter();
      ResultSet rs;
    /**
     * Creates new form Produits
     */
    public Produits() {
        initComponents();
        Table();
                     jTextField1.setVisible(false);
                     jTextField1.setEnabled(false);
                     jTextField6.setVisible(false);
                     jTextField6.setEnabled(false);
                     jTextField7.setVisible(false);
                     jTextField7.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jRadioButton2 = new javax.swing.JRadioButton();
        jTextField5 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Designation");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        jLabel2.setText("Reference");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 64, -1));

        jButton1.setBackground(new java.awt.Color(180, 133, 113));
        jButton1.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Ajouter");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 438, -1, -1));

        jButton2.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(180, 133, 113));
        jButton2.setText("Modifier");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 438, -1, -1));

        jButton3.setBackground(new java.awt.Color(180, 133, 113));
        jButton3.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Supprimer");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setFocusable(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 438, -1, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 145, -1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 145, -1));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 144, -1));

        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField1.setToolTipText("");
        getContentPane().add(jFormattedTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 118, -1));

        try {
            jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jFormattedTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 118, -1));

        jComboBox1.setBackground(new java.awt.Color(180, 133, 113));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lait cru", "Lailt pasteurisé", "Lait stérilisé", "Lait UHT", "Fromage", "crème fraiche", "Beurre", "Lait concentré", "Yaourt" }));
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBox1.setFocusable(false);
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 145, -1));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 402, 93, 25));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, -1, -1));
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 402, 87, 25));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, -1, -1));

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 402, 89, 25));
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, 63, -1));

        jRadioButton2.setBackground(new java.awt.Color(180, 133, 113));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Reference");
        jRadioButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButton2.setFocusable(false);
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 344, 89, 17));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 370, 196, 27));

        jButton4.setBackground(new java.awt.Color(180, 133, 113));
        jButton4.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Rechercher");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setFocusable(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 410, -1, -1));

        jLabel7.setText("Recherche par :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 340, -1, -1));

        jRadioButton1.setBackground(new java.awt.Color(180, 133, 113));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Designation");
        jRadioButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButton1.setFocusable(false);
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 340, -1, 22));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255,80));

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\BabaAhmed_Ghamraci\\pic\\icons8.png")); // NOI18N
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.setFocusable(false);
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        jLabel5.setText("Date de Peremption");

        jLabel4.setText("Date de Production ");

        jLabel3.setText("Valeur nut");

        jLabel6.setText("Poids net");

        jLabel11.setText("Stock");

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\BabaAhmed_Ghamraci\\pic\\icons8-ref30.png")); // NOI18N
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel5))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(123, 123, 123))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(26, 26, 26)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(127, 127, 127))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 430, 400));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255,80));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Designation", "Reference", "Val nut", "Date prod", "Date exp", "Poids", "Stock", "ing 1", "ing 2", "ing 3"
            }
        ));
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable1.setFocusable(false);
        jTable1.setSelectionBackground(new java.awt.Color(180, 133, 113));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable1MouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(177, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 520, 400));

        jLabel13.setFont(new java.awt.Font("Berlin Sans FB", 0, 50)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(180, 133, 113));
        jLabel13.setText("insertion des produits");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 450, 50));

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\BabaAhmed_Ghamraci\\pic\\azerCm.jpg")); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, -1, 700));

        setSize(new java.awt.Dimension(1014, 665));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
            if(jComboBox1.getSelectedItem().toString().length()!=0 && jTextField2.getText().length()!=0 &&jTextField3.getText().length()!=0 && jTextField4.getText().length()!=0 && jTextField8.getText().length()!=0 && !jFormattedTextField1.getText().equals("  -  -  ") &&  !jFormattedTextField2.getText().equals("  -  -  ")) {  
        String designation=jComboBox1.getSelectedItem().toString();
           String reference=jTextField2.getText();
           String valn=jTextField3.getText();
           String dateP=jFormattedTextField1.getText();
           String datePermp=jFormattedTextField2.getText();
           String poids=jTextField4.getText();
           String Stock=jTextField8.getText();
            String ing1=null;
           String ing2=null;
           String ing3=null;
           
           if(designation.equals("Lait concentré")||designation.equals("Yaourt") ||designation.equals("crème fraiche")||designation.equals("Beurre") || designation.equals("Fromage")){
         
         
                     
                  ing1=jTextField1.getText();
           ing2=jTextField6.getText();
           ing3=jTextField7.getText(); 
                     
           
            }
           
         int valN=Integer.parseInt(valn);
         int p=Integer.parseInt(poids);
         
          String requete="INSERT INTO `produits`(`designation`, `references`, `val_nut`, `date_production`, `date_peremption`, `poids`, `stock`, `ingredient1`, `ingredient2`, `ingredient3`,`prix`) VALUES ('"+designation+"','"+reference+"','"+valN+"','"+dateP+"','"+datePermp+"','"+p+"','"+Stock+"','"+ing1+"','"+ing2+"','"+ing3+"', 'non')" ;
       try{
          stmt=maConnection.obtenirconnexion().createStatement();
          stmt.executeUpdate(requete);
          JOptionPane.showMessageDialog(null,"Produit enregistré avec succès");
         Table();
       }catch(SQLException ex){
       System.err.println(ex);
        JOptionPane.showMessageDialog(null,"Le produit existe déja");
       
       }
       }else{
      JOptionPane.showMessageDialog(null,"Veuillez remplir tous les champs svp");
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here
        String designation=jComboBox1.getSelectedItem().toString();
        System.out.print(designation);
           String reference=jTextField2.getText();
           String valn=jTextField3.getText();
           String dateP=jFormattedTextField1.getText();
           String datePermp=jFormattedTextField2.getText();
           String poids=jTextField4.getText();
           String Stock=jTextField8.getText();
            String ing1=null;
           String ing2=null;
           String ing3=null;
           
            if(designation.equals("Lait concentré")||designation.equals("Yaourt") ||designation.equals("crème fraiche")||designation.equals("Beurre")){
         
                                 
           ing1=jTextField1.getText();
           ing2=jTextField6.getText();
           ing3=jTextField7.getText();
            }
         int valN=Integer.parseInt(valn);
         int p=Integer.parseInt(poids);
          String requete1="select* from `produits` WHERE `references`='"+reference+"' And `designation`='"+designation+"'";
         String requete2="UPDATE `produits` SET `designation`='"+designation+"',`val_nut`='"+valN+"',`date_production`='"+dateP+"', `date_peremption`='"+datePermp+"',`poids`='"+ p+"', `stock`='"+Stock+"', `ingredient1`='"+ing1+"', `ingredient2`='"+ing2+"',`ingredient3`='"+ing3+"' WHERE `references`='"+reference+"'";
       try{
          stmt=maConnection.obtenirconnexion().createStatement();
           rs=stmt.executeQuery(requete1);
          if(rs.next()) {
          stmt.executeUpdate(requete2);
          JOptionPane.showMessageDialog(null,"requete executée avec succès");
          Table();
          }else{
          JOptionPane.showMessageDialog(null,"le produit n'existe pas");
          }
       }catch(SQLException ex){
       System.err.println(ex);
       
       
       }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
       String reference= jTextField2.getText();
       
          String requete1="select* from `produits` WHERE `references`='"+reference+"'";

          String requete2="delete from `produits` WHERE `references`='"+reference+"'";
          try{
         
          stmt=maConnection.obtenirconnexion().createStatement();
            rs=stmt.executeQuery(requete1);
            if(rs.next()){
          stmt.executeUpdate(requete2);
          
          JOptionPane.showMessageDialog(null,"requete executée avec succès");
          
          Table();
            }else{
                JOptionPane.showMessageDialog(null,"le produit n'existe");
            }
         
          }catch(SQLException ex){
         
           System.err.println(ex);
         
          }
         
          
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseReleased
        // TODO add your handling code here:
        int i=jTable1.getSelectedRow();
        DefaultTableModel model =(DefaultTableModel)jTable1.getModel();
        //jTextField1.setText(model.getValueAt(i,0).toString());
        jComboBox1.setSelectedItem(model.getValueAt(i,0).toString());
        jTextField2.setText(model.getValueAt(i,1).toString());
        jTextField3.setText(model.getValueAt(i,2).toString());
        jFormattedTextField1.setText(model.getValueAt(i,3).toString());
        jFormattedTextField2.setText(model.getValueAt(i,4).toString());
        jTextField4.setText(model.getValueAt(i,5).toString());
        jTextField8.setText(model.getValueAt(i,6).toString());
        jTextField1.setText(model.getValueAt(i,7).toString());      
        jTextField6.setText(model.getValueAt(i,8).toString());
        
         jTextField7.setText(model.getValueAt(i,9).toString());
        
        
        
    }//GEN-LAST:event_jTable1MouseReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        String element= jTextField5.getText();
        String requete1="";
        if(jRadioButton2.isSelected() == true){
               requete1="select* from `produits` WHERE `references`='"+element+"'";
        }else{
           requete1="select* from `produits` WHERE `designation`='"+element+"'";
        }
        
        try{
        stmt=maConnection.obtenirconnexion().createStatement();
            rs=stmt.executeQuery(requete1);
           
           
             if(rs.next()){
          
         jComboBox1.setSelectedItem(rs.getString("designation"));
         jTextField2.setText(rs.getString("references"));
         jTextField3.setText(rs.getString("val_nut"));
         jFormattedTextField1.setText(rs.getString("date_production"));
         jFormattedTextField2.setText(rs.getString("date_peremption"));
         jTextField4.setText(rs.getString("poids"));
         jTextField8.setText(rs.getString("stock"));
           jTextField1.setText(rs.getString("ingredient1"));
           jTextField6.setText(rs.getString("ingredient2"));
           jTextField7.setText(rs.getString("ingredient3"));
         }
        }catch(SQLException ex){
         System.err.println(ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        String designation=jComboBox1.getSelectedItem().toString();
        
       
        //String ing1=null;
          // String ing2=null;
          // String ing3=null;
         if(designation.equals("Lait concentré")||designation.equals("Yaourt") ||designation.equals("crème fraiche")||designation.equals("Beurre")||designation.equals("Fromage")){
         
               jLabel8.setText("ingredient1");
              jLabel9.setText("ingredient2");
               jLabel10.setText("ingredient3");
                      jTextField1.setVisible(true);
                      jTextField1.setEnabled(true);
                      
                     jTextField6.setVisible(true);
                     jTextField6.setEnabled(true);
                     jTextField7.setVisible(true);
                     jTextField7.setEnabled(true);
                   
            }else{
             jLabel8.setText("");
              jLabel9.setText("");
               jLabel10.setText("");
                     jTextField1.setVisible(false);
                     jTextField1.setEnabled(false);
                     jTextField6.setVisible(false);
                     jTextField6.setEnabled(false);
                     jTextField7.setVisible(false);
                     jTextField7.setEnabled(false);
             
         }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        Agent fenetreAg = new Agent();
        fenetreAg.show();dispose();fenetreAg.setLocationRelativeTo(null);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        jFormattedTextField1.setText("");
        jFormattedTextField2.setText("");
        
        
    }//GEN-LAST:event_jLabel15MouseClicked

    
    public void Table(){
       
         String [] produit={"designation","reference","valeur nutritionnelle","date_prd","date_peremp","poids","stock","ingredient1","ingredient2","ingredient3"};
     String [] afficher=new String[10];
      DefaultTableModel model =new DefaultTableModel(null,produit);
       
    String requete="select * from `produits`";
     try{
       stmt=maConnection.obtenirconnexion().createStatement();
         rs=stmt.executeQuery(requete);
            while(rs.next()){
         afficher[0]=rs.getString("designation");
         afficher[1]=rs.getString("references");
         afficher[2]=rs.getString("val_nut");
         afficher[3]=rs.getString("date_production");
         afficher[4]=rs.getString("date_peremption");
         afficher[5]=rs.getString("poids");
         afficher[6]=rs.getString("stock");
         afficher[7]=rs.getString("ingredient1");
         afficher[8]=rs.getString("ingredient2");
         afficher[9]=rs.getString("ingredient3");
         model.addRow(afficher);
         }
             
        jTable1.setModel(model);
     }catch(SQLException ex){
     System.err.println(ex);
     
     }
   
    }
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Produits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Produits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Produits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Produits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Produits().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
